# Generated by Django 3.2.4 on 2021-06-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentdetails',
            name='alternate_phone_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='parentdetails',
            name='phone_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
